

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
     <>
     <h1>E-Com</h1>
      <div>{children}</div>
     </>
  )
}
